In [1]:
import torch
import numpy as np

# PyTorch Basic Tensor Manipulation
- Vector, Matrix and Tensor
- NumPy Review
- PyTorch Tensor Allocation
- Matrix Multiplication
- Other Basic Ops

## Vector, Matrix and Tensor
### PyTorch Tensor Shape Convention
- 2D Tensor (typical simple setting)
    - |t| = (batch size, dim)
- 3D Tensor (typical computer vision)
    - |t| = (batch size, width, height)
- 3D Tensor (typical natural language processing)
    - |t| = (batch size, length, dim 

### PyTroch Tensor
- pytorch에서 tensor를 만드는 것은 numpy와 동일하다.
- torch.FloatTensor()를 이용하면 1차원 2차원 3차원 등 을 많들 수 있다.

In [2]:
def check_torch(x):
    print(x)
    print(f'check type  : {type(x)}')
    print(f'check shape : {x.shape}')
    print(f'check dim   : {x.dim()}')
    print(f'check size  : {x.size()}')
    
def check_numpy(x):
    print(x)
    print(f'check type  : {type(x)}')
    print(f'check shape : {x.shape}')
    print(f'check dim   : {x.ndim}')
    print(f'check size  : {x.size}')

In [46]:
one_dim_torch = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
check_torch(one_dim_torch)
print()
one_dim_np = np.array([0.,1.,2.,3.,4.,5.,6.])
check_numpy(one_dim_np)


tensor([0., 1., 2., 3., 4., 5., 6.])
check type  : <class 'torch.Tensor'>
check shape : torch.Size([7])
check dim   : 1
check size  : torch.Size([7])

[0. 1. 2. 3. 4. 5. 6.]
check type  : <class 'numpy.ndarray'>
check shape : (7,)
check dim   : 1
check size  : 7


In [39]:
two_dim_torch = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
check_torch(two_dim_torch)
print(two_dim_torch[:,1:])
print(two_dim_torch[:,1:].size())
print(two_dim_torch[1,:])
print(two_dim_torch[1,:].size())


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
check type  : <class 'torch.Tensor'>
check shape : torch.Size([3, 3])
check dim   : 2
check size  : torch.Size([3, 3])
tensor([[2., 3.],
        [5., 6.],
        [8., 9.]])
torch.Size([3, 2])
tensor([4., 5., 6.])
torch.Size([3])


### Broadcasting
#### broadcasting은 자동으로 되기 때문에 주의해야 한다.


In [48]:
# Same shape
m1 = torch.FloatTensor([[1,2]])  # size = (1,2)
m2 = torch.FloatTensor([[2,1]])  # size = (1,2)
same_shape = m1+m2
check_torch(same_shape)
print()
# numpy
m3 = np.array([[1,2]])
m4 = np.array([[2,1]])
np_same_shape = m3+m4
check_numpy(np_same_shape)

tensor([[3., 3.]])
check type  : <class 'torch.Tensor'>
check shape : torch.Size([1, 2])
check dim   : 2
check size  : torch.Size([1, 2])

[[3 3]]
check type  : <class 'numpy.ndarray'>
check shape : (1, 2)
check dim   : 2
check size  : 2


In [53]:
# Vector + Scala
m1 = torch.FloatTensor([[1,2]])  # size = (1,2)
m2 = torch.FloatTensor([2])  # size = (1,)
same_shape = m1+m2  # m2 => [[2,2]]
check_torch(same_shape)
print()
# numpy
m3 = np.array([[1,2]])
m4 = np.array([2])
np_same_shape = m3+m4
check_numpy(np_same_shape)

tensor([[3., 4.]])
check type  : <class 'torch.Tensor'>
check shape : torch.Size([1, 2])
check dim   : 2
check size  : torch.Size([1, 2])

[[3 4]]
check type  : <class 'numpy.ndarray'>
check shape : (1, 2)
check dim   : 2
check size  : 2


In [54]:
# Matrix + Scalar
m1 = torch.FloatTensor([[1],[2]])  # size = (2,1)
m2 = torch.FloatTensor([2])  # size = (1,2)
same_shape = m1+m2
check_torch(same_shape)
print()
# numpy
m3 = np.array([[1],[2]])
m4 = np.array([2])
np_same_shape = m3+m4
check_numpy(np_same_shape)

tensor([[3.],
        [4.]])
check type  : <class 'torch.Tensor'>
check shape : torch.Size([2, 1])
check dim   : 2
check size  : torch.Size([2, 1])

[[3]
 [4]]
check type  : <class 'numpy.ndarray'>
check shape : (2, 1)
check dim   : 2
check size  : 2


In [55]:
# different shape matrix
m1 = torch.FloatTensor([[1,2]])  # size = (1,2)
m2 = torch.FloatTensor([[2],[1]])  # size = (2,1)
same_shape = m1+m2
check_torch(same_shape)
print()
# numpy
m3 = np.array([[1,2]])
m4 = np.array([[2],[1]])
np_same_shape = m3+m4
check_numpy(np_same_shape)

tensor([[3., 4.],
        [2., 3.]])
check type  : <class 'torch.Tensor'>
check shape : torch.Size([2, 2])
check dim   : 2
check size  : torch.Size([2, 2])

[[3 4]
 [2 3]]
check type  : <class 'numpy.ndarray'>
check shape : (2, 2)
check dim   : 2
check size  : 4


In [11]:
print('-------------')
print('Mul vs Matmul')
print('-------------')
print('Matmul')
m1 = torch.FloatTensor([[1,2],[3,4]])  # (2, 2)
m2 = torch.FloatTensor([[1],[2]])  # (2,1)
check_torch(m1)
check_torch(m2)
print(f'matmul : {m1.matmul(m2)}')  # (2,1) (2,2) * (2,1)의 행렬곱이 진행되어 2,1의 값이 나온다
print("Mul")
print(f'Mul : {m1*m2}, \n{m1.mul(m2)}')  # (2,1) (2,2) * (2,1)의 행렬곱이 진행되어 2,1의 값이 나온다

-------------
Mul vs Matmul
-------------
Matmul
tensor([[1., 2.],
        [3., 4.]])
check type  : <class 'torch.Tensor'>
check shape : torch.Size([2, 2])
check dim   : 2
check size  : torch.Size([2, 2])
tensor([[1.],
        [2.]])
check type  : <class 'torch.Tensor'>
check shape : torch.Size([2, 1])
check dim   : 2
check size  : torch.Size([2, 1])
matmul : tensor([[ 5.],
        [11.]])
Mul
Mul : tensor([[1., 2.],
        [6., 8.]]), 
tensor([[1., 2.],
        [6., 8.]])


In [12]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [16]:
# Can't use mean() on integers
t_lt = torch.LongTensor([1,2])  # LongTensor가 정수형 64비트의 자료형이기 때문에 소수점이 나올 수 없다.
try:
    print(t_lt.mean())
except Exception as exc:
    print(exc)
print('''
텐서에는 자료형이라는 것이 있습니다. 각 데이터형별로 정의되어져 있는데, 
예를 들어 32비트의 부동 소수점은 torch.FloatTensor를, 64비트의 부호 있는 정수는 torch.LongTensor를 사용합니다. 
GPU 연산을 위한 자료형도 있습니다. 
예를 들어 torch.cuda.FloatTensor가 그 예입니다.
''')

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

텐서에는 자료형이라는 것이 있습니다. 각 데이터형별로 정의되어져 있는데, 
예를 들어 32비트의 부동 소수점은 torch.FloatTensor를, 64비트의 부호 있는 정수는 torch.LongTensor를 사용합니다. 
GPU 연산을 위한 자료형도 있습니다. 
예를 들어 torch.cuda.FloatTensor가 그 예입니다.



In [22]:
t_matrix = torch.LongTensor([[1,2],[3,4]]).float()
print(t_matrix.mean())
print(t_matrix.mean(dim=0)) # dim=0 인 것은 0번째 차원을 없앤고 출력 해봐라는 것. np의 axis와 같은 개념
# (2,2) => (1,2) or (2,)
print(t_matrix.mean(dim=1))
# (2,2) => (2,1)
print(t_matrix.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [30]:
s = np.array([[1,2],[3,4]])
check_numpy(s)
print(s.mean())
print(s.sum(axis=0), s.mean(axis=0))
check_numpy(s.sum(axis=0))
print(s.sum(axis=1), s.mean(axis=1))
print(s.sum(axis=-1), s.mean(axis=-1))

[[1 2]
 [3 4]]
check type  : <class 'numpy.ndarray'>
check shape : (2, 2)
check dim   : 2
check size  : 4
2.5
[4 6] [2. 3.]
[4 6]
check type  : <class 'numpy.ndarray'>
check shape : (2,)
check dim   : 1
check size  : 2
[3 7] [1.5 3.5]
[3 7] [1.5 3.5]
